### ISSUE TITLE
Support for digest authentication

### ISSUE THREAD

**Issue by wdmnn** [bartbutenaers/node-red-contrib-multipart-stream-decoder#5]
Unfortunately I cannot get the decoder to work as my camera requires digest authentication but the node only supports basic.
Maybe it's possible to somehow integrate this :)

**Comment by bartbutenaers** [comment]
Hi @wdmnn,

Indeed I experienced a few months ago that digest authentication is not supported.  So I created a new branch _"use_request_library"_ for this node, to use another library under the hood.  That branch supports digest authentication, but I had to hardcoded this (see [code](https://github.com/bartbutenaers/node-red-contrib-multipart-stream-decoder/blob/use_request_library/multipart_decoder.js#L254)):
```
sendImmediately: false
```
However since  this node is very similar to the HttpRequest node, I opened a [discussion ](https://discourse.nodered.org/t/digest-authentication-support-in-httprequest-node/4131) about it on the Node-RED forum.  As a result both the HttpRequest node and my StreamDecoder node needs to have e.g. a dropdown with 'base authentication', 'digest authentication', ... (intead of hardcoding it).  But due to a lack of time I didn't continue the discussion.  It is still on my todo list ...

You can install the branch and let me konw if it works.  And you are always welcome to continue the discussion on the Node-RED forum if you like, and then I will join you over there ...

Bart

**Comment by inwaar** [comment]
Hi bartbutenaers, I tried the branch and it works as expected with the digest authentication. Any chance it's merged to master?

**Comment by inwaar** [comment]
I don't know if this is related to the branch but if I change anything for the `multipart-stream-decoder` node and re-deploy flows I get NodeRed process crashed with the following:
```
25 Jul 16:18:55 - TypeError: Cannot read property 'resume' of null
    at Timeout._onTimeout (/home/user/nodered/node_modules/node-red-contrib-multipart-stream-decoder/multipart_decoder.js:576:50)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

this is also the case if I send {stop: true} payload to the node - getting the nodered processed entirely crashed

**Comment by bartbutenaers** [comment]
Hey Igor,
Probably I will never merge this branch to master.  Reason is very simple: the "request" library is meanwhile also not maintained anymore :-(
The http-request core module has the same problem, as you can see in this [discussion](https://discourse.nodered.org/t/should-node-red-nodes-use-http-request-or-got/25392/3?u=bartbutenaers) on the Node-RED forum.  Since my node is closely related to the http-request node, I'm kind of waiting which library they will start using.  They talk about the "got" library, but I haven't found anything about digest or bearer support in that library.  And nobody has volunteered yet in that discussion...
But you can always ask in that discussion if there is any work in progress.

**Comment by bartbutenaers** [comment]
From this [issue](https://github.com/node-red/node-red/issues/2481) it seems they will migrate to the Axios module in Node-RED 1.2

**Comment by jrhodnik** [comment]
Has there been any progress on this front? Needing Digest auth for a network camera.

**Comment by bartbutenaers** [comment]
Hi @jrhodnik,
I have the same issue myself, so I have been looking at the Axios module, since that might be used for the http-request node in the future.  However if I'm not mistaken Axios doesn't support (decently) digest authentication...  So it is not clear to me how they want to solve that when they would start using Axios for the http-request module. 
If anybody knows an answer for this, please share it here.  Or start a discussion on the Node-RED community (about the http-request node)...
Bart

**Comment by Sineos** [comment]
Hoping for a Digest Auth as well. Would https://www.npmjs.com/package/urllib be an option?
Anyway big thanks for this contribution

**Comment by bartbutenaers** [comment]
Hi @Sineos,
The main problem is that nobody in the community is willing to help upgrading the http-request node.
Indeed that ***urllib*** package contains digest authentication, but at the time being I have added (see this [PR](https://github.com/node-red/node-red/pull/2061)) not only Digest authentication but also Bearer token authentication to the http-request node.  And I don't think the urllib supports both...
It is pretty simple: LOTS of people are using Node-RED, but only a VERY limited number of them is contributing to Node-RED.  If nobody volunteers to figure out how to upgrade the http-request node, then this multipart-stream-decoder won't be fixed either ...

**Comment by Sineos** [comment]
Thanks for coming back to this. 
In any case, the request-branch works fine for me.

**Comment by bartbutenaers** [comment]
Hi @Gun-neR,
About your [question](https://github.com/bartbutenaers/node-red-contrib-multipart-stream-decoder/issues/11), I will post an update here.

In Node-RED 2.x.x the http-request node has finally been migrated: it is not based anymore on the old obsolete "request" library, but now they use the maintained "got" library.  In the last two weeks (since the release of 2.x.x) there have been a LARGE number of issues with the http-request node, but they are all being solved very quickly by Nick and Ben.  And they publish every couple of days a new minor release to publish those changes.  So I expect the http-request to become stable in a few weeks.

Since the multipart-stream-decoder node is a fork of the http-request node, I had to wait for this migration in order to be able to update my node.  And when you see the amount of works that those full-time developers had to spend on the migration, there is no way I could have done this somewhere in my limited free time.  That is why this issue has been postponed so long.

But the story is not finished yet.  Nick has [mentioned](https://twitter.com/knolleary/status/1417828854111129604) on twitter that the "got" library has now announced to move away from CommonJs modules to Ecmascript modules.  So to avoid that the http-request node is stuck with an obsolete version of the "got" library, they will have to update the http-rquest node one more time...

So I need to wait for that version (build on the ESM version of "got"), otherwise I have to upgrade my node also twice.  And I don't have the time to do a series of migrations...

Once the http-request node is stable, I will "try" to find some time to migrate the decoder node and add the digest authentication (similar to how I added that feature to the http-request node a long time ago via [this](https://github.com/node-red/node-red/pull/2061) PR).

**Comment by Gun-neR** [comment]
Sounds good.  I am still playing around with NR, so no rush for me.  Thank you for the efforts.
